name: .NET

on:
  push:
    branches: [ master, dev, feature/*, fix/*, release/* ]
    
  pull_request:
    branches: [ master ]
    
  release:
    types: [ published ]
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    # Create Local NuGet Source
    
    - name: Create Local NuGet Directory
      run: mkdir ~/nuget
      
    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget
      
    # Primitives
    
    - name: Restore Primitives
      run: dotnet restore ./src/*/*/Primitives.csproj

    - name: Build Primitives
      run: dotnet build ./src/*/*/Primitives.csproj --no-restore  -c Release

    - name: Pack Primitives
      run: dotnet pack ./src/*/*/Primitives.csproj --no-restore -o ~/nuget  -c Release
      
    - name: Restore Primitives.Tests
      run: dotnet restore ./src/*/*/Primitives.Tests.csproj

    - name: Test Primitives.Tests
      run: dotnet test ./src/*/*/Primitives.Tests.csproj --no-restore  -c Release
      
      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetSourcePassword }} --skip-duplicate
